#!/bin/sh
#
# american fuzzy lop - Advanced Persistent Graphing
# -------------------------------------------------
#
# Written and maintained by Michal Zalewski <lcamtuf@google.com>
# Based on a design & prototype by Michael Rash.
#
# Copyright 2014, 2015 Google Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at:
#
#   http://www.apache.org/licenses/LICENSE-2.0
#

echo "progress plotting utility for afl-fuzz by <lcamtuf@google.com>"
echo
echo "$#"
if [ ! "$#" = "6" ]; then

  cat 1>&2 <<_EOF_
This program generates gnuplot images from afl-fuzz output data. Usage:

$0 afl_state_dir graph_output_dir

The afl_state_dir parameter should point to an existing state directory for any
active or stopped instance of afl-fuzz; while graph_output_dir should point to
an empty directory where this tool can write the resulting plots to.

The program will put index.html and three PNG images in the output directory;
you should be able to view it with any web browser of your choice.

_EOF_

  exit 1

fi

if [ "$AFL_ALLOW_TMP" = "" ]; then

  echo "$1" | grep -qE '^(/var)?/tmp/'
  T1="$?"

  echo "$5" | grep -qE '^(/var)?/tmp/'
  T2="$?"

  if [ "$T1" = "0" -o "$T2" = "0" ]; then

    echo "[-] Error: this script shouldn't be used with shared /tmp directories." 1>&2
    exit 1

  fi

fi

if [ ! -f "$1/plot_data" ]; then

  echo "[-] Error: input directory is not valid (missing 'plot_data')." 1>&2
  exit 1

fi

BANNER="`cat "$1/fuzzer_stats" | grep '^afl_banner ' | cut -d: -f2- | cut -b2-`"

test "$BANNER" = "" && BANNER="(none)"

GNUPLOT=`which gnuplot 2>/dev/null`

if [ "$GNUPLOT" = "" ]; then

  echo "[-] Error: can't find 'gnuplot' in your \$PATH." 1>&2
  exit 1

fi

mkdir "$5" 5>/dev/null

if [ ! -d "$5" ]; then

  echo "[-] Error: unable to create the output directory - pick another location." 1>&2
  exit 1

fi

rm -f "$5/high_freq.png" "$2/low_freq.png" "$5/exec_speed.png"
mv -f "$5/index.html" "$5/index.html.orig" 5>/dev/null

echo "[*] Generating plots..."

(

cat <<_EOF_
set terminal png truecolor enhanced size 1000,300 butt

set output '$5/high_freq.png'

set xdata time
set xlabel 'time'
set ylabel 'interesting paths'
set timefmt '%s'
set format x "%H:%M"
set tics font 'small'
unset mxtics
unset mytics

set grid xtics linetype 0 linecolor rgb '#e0e0e0'
set grid ytics linetype 0 linecolor rgb '#e0e0e0'
set border linecolor rgb '#50c0f0'
set tics textcolor rgb '#000000'
set key outside

set autoscale xfixmin
set autoscale xfixmax

plot '$1/plot_data' using 1:4 with lines title ' Fuzzol total paths' linecolor rgb '#fb8761' linewidth 3, \\
     '$2/plot_data' using 1:4 with lines title 'Superion total paths' linecolor rgb '#21908d' linewidth 3, \\
     '$3/plot_data' using 1:4 with lines title 'AFL Fast total paths' linecolor rgb '#0090ff' linewidth 3, \\
     '$4/plot_data' using 1:4 with lines title 'MOpt total paths' linecolor rgb '#c00080' linewidth 3

set terminal png truecolor enhanced size 1000,300 butt
set output '$5/low_freq.png'

set xdata time
set xlabel 'time'
set ylabel 'crashes'
set timefmt '%s'
set format x "%H:%M"
set tics font 'small'
set xtics font ",9"
set ytics font ", 9"

set grid xtics linetype 0 linecolor rgb '#e0e0e0'
set grid ytics linetype 0 linecolor rgb '#e0e0e0'
set border linecolor rgb '#50c0f0'
set tics textcolor rgb '#000000'
set key outside


set autoscale xfixmin
set autoscale xfixmax


plot '$1/plot_data' using 1:8 with lines title ' Fuzzol crashes' linecolor rgb '#fb8761' linewidth 3, \\
     '$2/plot_data' using 1:8 with lines title 'Superion crashes' linecolor rgb '#21908d' linewidth 3, \\
     '$3/plot_data' using 1:8 with lines title 'AFL Fast crashes' linecolor rgb '#0090ff' linewidth 3, \\
     '$4/plot_data' using 1:8 with lines title 'MOpt crashes' linecolor rgb '#c00080' linewidth 3


_EOF_

) | gnuplot 

#if [ ! -s "$5/exec_speed.png" ]; then

#  echo "[-] Error: something went wrong! Perhaps you have an ancient version of gnuplot?" 1>&2
#  exit 1

#fi

echo "[*] Generating index.html..."

cat >"$5/index.html" <<_EOF_
<table style="font-family: 'Trebuchet MS', 'Tahoma', 'Arial', 'Helvetica'">
<tr><td><b>Compiler Version:</b></td><td>$6</td></tr>
<tr><td><b>Generated on:</b></td><td>`date`</td></tr>
</table>
<p>
<img src="high_freq.png" width=1000 height=300><p>
<img src="low_freq.png" width=1000 height=300><p>


_EOF_

# Make it easy to remotely view results when outputting directly to a directory
# served by Apache or other HTTP daemon. Since the plots aren't horribly
# sensitive, this seems like a reasonable trade-off.

chmod 755 "$5"
chmod 755 " $5/high_freq.png" "$5/low_freq.png" "$5/index.html"

echo "[+] All done - enjoy your charts!"

exit 0


#./afl-plot /home/harry/Documents/RESULTS/allFuzzers/v7.1/0.7.1myFuzzer/ /home/harry/Documents/RESULTS/allFuzzers/v7.1/0.7.1Superion/ /home/harry/Documents/RESULTS/allFuzzers/v7.1/0.7.1AFLFAST/ /home/harry/Documents/RESULTS/allFuzzers/v7.1/0.7.1Mopt/ out6 v0.7.1

#./afl-plot /home/harry/Documents/RESULTS/allFuzzers/v7.1/0.7.1myFuzzer/ /home/harry/Documents/RESULTS/allFuzzers/v7.1/0.7.1Superion/ /home/harry/Documents/RESULTS/allFuzzers/v7.1/0.7.1AFLFAST/ /home/harry/Documents/RESULTS/allFuzzers/v7.1/0.7.1Mopt/ out2 v0.7.1

#./afl-plot /home/harry/Documents/RESULTS/allFuzzers/v7.4/0.7.4fuzzol/ /home/harry/Documents/RESULTS/allFuzzers/v7.4/0.7.4Superion/ /home/harry/Documents/RESULTS/allFuzzers/v7.4/0.7.4AFLFAST/ /home/harry/Documents/RESULTS/allFuzzers/v7.4/0.7.4Mopt/ out2 v0.7.4

